# Generated by Django 4.1.4 on 2023-03-01 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_appointment_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.DateField(default=datetime.datetime(2023, 3, 1, 21, 25, 0, 225486)),
        ),
    ]
