# Generated by Django 4.1.4 on 2023-03-01 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_appointment_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.DateField(default=datetime.datetime(2023, 3, 1, 23, 44, 49, 12962)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('HIFU Face', 'HIFU Face'), ('HIFU Body', 'HIFU Body'), ('HIFU Vaginal', 'HIFU Vaginal'), ('HIFU 5D Face', 'HIFU 5DFace'), ('HIFU Fat Reduction', 'HIFU Fat Reduction'), ('HIFU Vagin', 'HIFU Vagin'), ('Microneedling Face', 'Microneedling Face'), ('Microneedling Body', 'Microneedling Body'), ('Hydro Facial', 'Hydro Facial')], default='HIFU Face', max_length=50),
        ),
    ]
