# Generated by Django 4.1.4 on 2023-03-01 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_appointment_day_alter_appointment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.DateField(default=datetime.datetime(2023, 3, 1, 23, 53, 52, 102825)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('HIFU Face', 'HIFU Face'), ('HIFU Body', 'HIFU Body'), ('HIFU Vaginal', 'HIFU Vaginal'), ('HIFU 5D Face', 'HIFU 5D Face'), ('HIFU Fat Reduction', 'HIFU Fat Reduction'), ('Microneedling Face', 'Microneedling Face'), ('Microneedling Body', 'Microneedling Body'), ('Hydro Facial', 'Hydro Facial')], default='HIFU Face', max_length=50),
        ),
    ]
