# Generated by Django 4.1.4 on 2023-03-01 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_appointment_day_alter_appointment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.DateField(default=datetime.datetime(2023, 3, 1, 23, 57, 18, 881865)),
        ),
    ]
