# Generated by Django 4.1.4 on 2023-03-03 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_appointment_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.DateField(default=datetime.datetime(2023, 3, 3, 23, 28, 16, 199667)),
        ),
    ]
